// The run (§1, loop B) — floors, nodes, recovery, XP, recruits, and the end of a run.
//
// This is the layer that was missing. Everything here lived in `DungeonScene` because the run loop
// grew a node at a time inside the only thing that was drawing one, and the cost showed up the
// moment anything else needed it: the progression tests had to reimplement `afterBattle` line for
// line just to play a floor, which is duplication across the §8 boundary — the exact thing that
// rule exists to prevent.
//
// The contract is the one the rest of the sim already uses. `arriveAt()` resolves a node
// completely, including the battle, and returns a **report**. The scene reads the report and plays
// it back; it decides nothing. Same shape as `resolveTick → events`, one loop up.
//
// Pure JS. No clock, no Math.random, no Phaser.

import { generateFloor, routeThrough } from './dungeon.js'
import { makeParty, makeFoes, addRecruits } from './party.js'
import { awardXp } from './progression.js'
import { createBattle } from './combat/battle.js'
import { runBattle } from './combat/resolve.js'
import { makeRng } from './kernel/rng.js'
import { DEFAULT_DOCTRINE, normalize } from './doctrine.js'
import { assignFormation } from './combat/formation.js'
import { battleCoin, treasureCoin, discoveriesFrom, endRun } from './economy.js'
import { createLedger, recordBattle, writeOnly } from './signals.js'
import { raise } from './dispatch.js'

/**
 * Node types that cut to the battle screen (§1, loop A), and how many foes each fields.
 *
 * A boss is one unit and nothing else (§6.3) — the count is 1 rather than 6 because a boss node
 * used to field six ordinary foes, which is a large encounter wearing a boss's name. Everything
 * that makes it a boss is on the def: the flag, the phases, persuade immunity.
 */
export const BATTLE_NODES = { encounter: 3, elite: 5, rare: 4, boss: 1 }

/**
 * A run starts short-handed on purpose: the party you finish with is the one you talked into
 * joining (§2), so the opening three are a seed rather than a squad.
 */
export const STARTING_PARTY = ['core:tomb_knight', 'core:bone_chanter', 'core:frost_sprite']

/**
 * @param {object} opts
 * @param {object} opts.kernel
 * @param {object} opts.tuning
 * @param {number|string} [opts.seed]
 * @param {string[]} [opts.starters]
 * @param {object} [opts.doctrine]
 * @param {object} [opts.state]  a run state loaded from a save (§14) — resumed rather than rebuilt.
 *   `floor` and `route` are absent from it on purpose and are regenerated by `enterFloor`.
 * @param {object} [opts.signals]  the profile's signal ledger (§4.3). One is made if none is given,
 *   so a headless run always has somewhere to notice things — and so `arriveAt` never branches on
 *   whether a ledger exists.
 * @returns {object} a run controller — `.state` is the serialisable half (§14)
 */
export function createRun ({ kernel, tuning, seed = 0, starters = STARTING_PARTY, lvl = 2, doctrine = DEFAULT_DOCTRINE, trace = null, state = null, signals = null } = {}) {
  // Normalised once, here, rather than defaulted field by field at eleven call sites. Everything
  // downstream — policy, formation, the route — may assume the full §4 shape.
  const policy = normalize(doctrine)
  trace?.beginRun()

  const ledger = signals ?? createLedger()
  ledger.beginRun()

  const run = {
    kernel,
    tuning,
    doctrine: policy,
    trace,
    /** The signal ledger (§4.3). Written by the run, read only by dispatches — never by combat. */
    signals: ledger,

    /**
     * Everything a save has to carry. `floor` and `route` are deliberately excluded: both are
     * regenerated from `(seed, floorNum)`, so persisting them would be storing a derivation and
     * inviting it to drift from the generator that made it.
     *
     * A resumed run adopts a loaded state wholesale rather than merging field by field, so there is
     * exactly one shape and `save.js`'s repair pass is the only thing that ever edits it.
     */
    state: state ?? {
      seed,
      floorNum: 1,
      visited: 0,
      deepest: 1,
      over: false,
      reason: null,
      /** In-run only, never banked (§5). Nothing sells anything until M6 ships items. */
      coin: 0,
      /** Codex keys this run turned up (§5) — the currency a losing run still produces. */
      discovered: [],
      /** Kin → spawn weight multiplier, from the Lattice's Bias nodes (§5). Empty until M5. */
      bias: null,
      /** What the run paid out, once `finish()` has priced it. Null while it is still going. */
      banked: null,
      roster: makeParty(kernel, starters, { side: 'party', lvl, formation: policy.formation })
    },

    floor: null,
    route: [],

    enterFloor: () => enterFloor(run),
    arriveAt: (node) => arriveAt(run, node),
    descend: () => descend(run),
    finish: () => finish(run),
    nodes: () => run.route.map((leg) => leg.to),
    setDoctrine: (next) => setDoctrine(run, next)
  }
  return run
}

/**
 * Which dispatches are true, as of right now (§4.1).
 *
 * On the controller rather than in the scene for the §18.15 reason: deciding that something is worth
 * reporting reads the ledger and the Doctrine, and a decision is not playback. The renderer shows
 * what comes back and never works out what to say.
 */
export function dispatches (run) {
  return raise({ kernel: run.kernel, ledger: run.signals, doctrine: run.doctrine, floor: run.state.floorNum })
}

/**
 * Close the run and price it (§5, loop B → loop C).
 *
 * On the controller rather than left to the caller because pricing a run is a decision, and §18.15
 * bans the renderer from making one. The scene shows `state.banked`; it never computes it. Idempotent,
 * so a scene that ends a run twice — a wipe on the same node as a boss kill — cannot double-pay.
 */
export function finish (run) {
  const first = !run.state.over || run.state.banked === null
  run.state.over = true
  run.state.reason ??= 'cleared'
  run.state.banked ??= endRun(run)
  // Idempotent for the same reason the payout is: a scene that ends a run twice must not double the
  // count any more than it doubles the Residue.
  if (first) run.signals.emit('run:end', { floor: run.state.deepest, reason: run.state.reason })
  return run.state.banked
}

/**
 * Adopt a rewritten Doctrine mid-run (§4 — the editor writes, the run reads).
 *
 * Formation is applied immediately because a pin is a statement about where a unit stands *now*;
 * everything else is read at the point it is used, so a rule edited between nodes is in force for
 * the next fight and never halfway through the current one. The caller decides when that is — the
 * renderer calls this at a node boundary, never while a timeline is playing back.
 */
export function setDoctrine (run, next) {
  run.doctrine = normalize(next)
  assignFormation(run.state.roster, run.kernel.registry, run.doctrine.formation)
  return run.doctrine
}

/** Generate the floor the run is standing on and the order it will walk the nodes in. */
export function enterFloor (run) {
  const { seed, floorNum } = run.state
  const every = run.tuning.spawn.bossEvery
  run.floor = generateFloor({ seed, floor: floorNum, boss: every > 0 && floorNum % every === 0 })
  // The route is the Route/Risk editor's output (§4): which nodes are worth walking to, and when
  // to stop and take the stairs.
  run.route = routeThrough(run.floor, run.floor.entry, {
    risk: run.doctrine.route?.order,
    skip: run.doctrine.route?.skip ?? [],
    maxNodes: run.doctrine.route?.maxNodes ?? null
  })
  run.state.visited = 0
  run.state.deepest = Math.max(run.state.deepest, floorNum)
  return run.floor
}

/**
 * Resolve one node completely and report what happened.
 *
 * For a battle node this runs the whole fight here, in pure JS, before anything is drawn — which is
 * §8's rule applied one level up from `resolveTick`. The renderer receives a finished timeline and
 * a finished consequence, and can only choose how fast to show them.
 *
 * @returns {{type, battle, awards, levelled, joined, cut, declined, healed, revived, wiped}}
 */
export function arriveAt (run, node) {
  run.state.visited++
  const report = {
    type: node.type,
    battle: null,
    awards: [],
    levelled: [],
    joined: [],
    cut: [],
    declined: [],
    healed: 0,
    revived: 0,
    coin: 0,
    discovered: [],
    wiped: false
  }

  if (BATTLE_NODES[node.type]) Object.assign(report, fight(run, node))
  else if (node.type === 'campfire') Object.assign(report, campfire(run))
  else if (node.type === 'treasure') report.coin = bank(run, treasureCoin(run.state.floorNum, run.tuning))

  // ★ Filled after the node resolved and never before it (§4.1). Everything a report describes has
  // already happened by the time the report exists, which is the entire difference between this and
  // a prompt — and the reason a headless run can carry the same field and read none of it.
  report.dispatches = dispatches(run)
  return report
}

/** Down the stairs. @returns {boolean} whether the run is still going. */
export function descend (run) {
  if (run.state.over) return false

  run.signals.emit('floor:cleared', { floor: run.state.floorNum })
  // "The campfire before the stairs is the decision" (§6.1). Descending hurt is what makes that
  // sentence true, and it is the pattern Pathfinding exists to have an opinion about.
  const standing = run.state.roster.filter((u) => u.hp > 0)
  const pct = standing.length
    ? standing.reduce((n, u) => n + u.hp / u.maxHp, 0) / standing.length
    : 0
  if (pct < (run.tuning.run?.woundedDescent ?? 0.5)) {
    run.signals.emit('descend:wounded', { floor: run.state.floorNum, hpPct: pct, down: run.state.roster.length - standing.length })
  }

  run.state.floorNum++
  enterFloor(run)
  return true
}

// ── nodes ───────────────────────────────────────────────────────────────────────────────────────

function fight (run, node) {
  const { kernel, tuning } = run
  const boss = node.type === 'boss'

  // A stream named for this exact node: which fight you get cannot depend on how much randomness
  // the walk to it happened to use (§11.7).
  const rng = makeRng(`${run.state.seed}|f${run.state.floorNum}|${node.x},${node.y}`)
  const foes = makeFoes(kernel, rng.stream('spawn'), {
    floor: run.state.floorNum, size: BATTLE_NODES[node.type], tuning, boss, bias: run.state.bias
  })

  const battle = createBattle({
    kernel, tuning, party: run.state.roster, foes, seed: run.state.seed, floor: run.state.floorNum, boss
  })
  const result = runBattle(battle, {
    kernel,
    tuning,
    rng: rng.stream('combat'),
    doctrine: run.doctrine,
    trace: run.trace,
    // Write-only (§4.3): content may raise a signal from inside a fight through `core:emit_signal`,
    // and nothing inside the fight can read one back.
    signals: writeOnly(run.signals)
  })

  return { battle: { result, foes }, ...applyOutcome(run, result, { node, foes }) }
}

/**
 * A battle's consequences, in the order they have to happen.
 *
 * The ordering is not cosmetic. Wounds land first because everything after reads HP; recovery is
 * next so the XP award sees who is actually standing; XP comes before recruits because someone
 * talked round mid-fight was on the other side for it and must not draw a share of the XP for its
 * own defeat (§3).
 */
export function applyOutcome (run, result, { node = null } = {}) {
  const { kernel, tuning, doctrine } = run

  // The resolver worked on copies, so this is the one place the run's state learns what happened.
  for (const u of run.state.roster) {
    const after = result.state.units.find((x) => x.uid === u.uid)
    if (after) u.hp = after.hp
  }

  // Survivors of a won fight patch themselves up a little (§6.1). Without this every run died on
  // node 2 of floor 1 on residual damage, before it could assemble a party at all.
  let healed = 0
  if (result.state.winner === 'party') {
    const back = tuning.run?.postBattleHeal ?? 0
    for (const u of run.state.roster) {
      if (u.hp <= 0) continue
      const before = u.hp
      u.hp = Math.min(u.maxHp, u.hp + Math.ceil(u.maxHp * back))
      healed += u.hp - before
    }
  }

  const { awards } = awardXp(kernel, run.state.roster, result.state, { tuning, doctrine })

  // The cap and the cut rule live in the sim; the report only says what they decided (§2).
  const grown = addRecruits(kernel, run.state.roster, result.state, { tuning, doctrine })
  run.state.roster = grown.roster

  // Coin and Codex are read from the finished battle rather than accumulated during it, so a fight
  // that is re-simmed for the post-mortem's counterfactual (§4.2) prices identically without the
  // resolver needing to know either currency exists.
  const coin = bank(run, battleCoin(kernel.registry, result.state, run.state.floorNum, tuning))
  const discovered = discoveriesFrom(kernel.registry, result)
  for (const key of discovered) {
    if (!run.state.discovered.includes(key)) run.state.discovered.push(key)
  }

  const wiped = run.state.roster.every((u) => u.hp <= 0)
  if (wiped) {
    run.state.over = true
    run.state.reason = 'wipe'
  }
  // Killing the boss ends the run at the bottom of the dungeon rather than at the stairs, and it is
  // the gate prestige unlocks behind (§5). Recorded as its own reason so the post-mortem can tell a
  // finished run from one that merely ran out of floors.
  if (node?.type === 'boss' && result.state.winner === 'party') {
    run.state.over = true
    run.state.reason = 'boss'
  }

  const out = {
    awards,
    levelled: awards.filter((a) => a.to > a.from),
    joined: grown.joined,
    cut: grown.cut,
    declined: grown.declined,
    healed,
    coin,
    discovered,
    wiped
  }

  // What the sim noticed (§4.3), read off the finished fight rather than accumulated during it —
  // the same argument `battleCoin` makes two blocks up. A battle re-simmed for the post-mortem's
  // counterfactual (§4.5) prices and *reports* identically without the resolver knowing either
  // system exists.
  recordBattle(run.signals, {
    registry: kernel.registry,
    tuning,
    result,
    report: { ...out, type: node?.type },
    floor: run.state.floorNum
  })

  return out
}

/** Add Coin to the run and return what was added, so a report can name it. */
function bank (run, amount) {
  run.state.coin += amount
  return amount
}

function campfire (run) {
  const t = run.tuning.run ?? {}
  let healed = 0
  let revived = 0
  for (const u of run.state.roster) {
    const before = u.hp
    if (u.hp > 0) {
      u.hp = Math.round(u.maxHp * (t.campfireHeal ?? 1))
    } else {
      // The fallen get picked back up here — the only place in a floor that they do.
      u.hp = Math.ceil(u.maxHp * (t.campfireRevive ?? 0))
      if (u.hp > 0) revived++
    }
    healed += Math.max(0, u.hp - before)
  }
  return { healed, revived }
}

// ── headless ────────────────────────────────────────────────────────────────────────────────────

/**
 * Play a whole run with no renderer — what `tools/sim.js`, the balance harness and the Worker call
 * (§1, loop D). The browser walks the same functions one node at a time so it can animate between
 * them; there is no second implementation of the run anywhere.
 *
 * @returns {{run, floors: number, reason: string, reports: Array}}
 */
export function playRun (run, { maxFloors = 8, onReport = null } = {}) {
  const reports = []
  enterFloor(run)

  while (!run.state.over && run.state.floorNum <= maxFloors) {
    for (const node of run.nodes()) {
      const report = arriveAt(run, node)
      reports.push(report)
      onReport?.(report, run)
      if (run.state.over) break
    }
    if (run.state.over) break
    if (run.state.floorNum === maxFloors) break
    descend(run)
  }

  const banked = finish(run)
  // ★ The M3.5 gate in one line: a headless run raises dispatches into the same queue a player
  // would see and reads none of them (§4.1). Nothing downstream touches this array, and that is the
  // assertion — an ignored report must cost the run nothing.
  const cards = reports.flatMap((r) => r.dispatches ?? [])
  return { run, floors: run.state.deepest, reason: run.state.reason, reports, banked, dispatches: cards }
}
